name: Tobias Federsel
favicon: null
layout_spectrum: 0.0966833159327507
typography_spectrum: 0.2437182548455894
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.17882632208056748
  lightness: 0.15107706235721707
  saturation: 0.6972657712176442
  rhythmicContrast: 0.740780831547454
purpose: []
